version: '3'
services:
  mariadb:
    image: mariadb:11.2.2
    networks:
      - api_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  api-server:
    image: api-server:0.0.1-SNAPSHOT
    networks:
      - api_network
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/api_server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
networks:
  api_network:
    driver: bridge