spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: None
            client-secret: None
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile
              - account_email
          naver:
            client-name: naver
            client-id: None
            client-secret: None
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
app:
  firebase-configuration-file: /app/firebase-adminsdk.json
  firebase-bucket: spring-api-server.appspot.com
  firebase-storage-uri: https://firebasestorage.googleapis.com/v0/b/
front:
  redirect-uri:
    host: cash.sundry.ninja
#    host: localhost
    port: 443
#    port: 3000
    path:
      signin: social/signin
      mapping: social/mapping
line:
  noti:
    token: None
