spring:
  profiles:
    active: local
    include: oauth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100
#    show-sql: true
  jwt:
    scret: hjjJWT
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#    org:
#      hibernate:
#        SQL: debug
server:
  port: 443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-type: PKCS12
    key-store-password: None
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

--- #local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/api_server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    username: hjj1991
    password: wowjddl1
decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  level:
    root: info
    c: error
    com.hjj.apiserver: debug

--- #prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
#    username: root
#    password: kHxLwtCsXafkwjWtaJae
#    url: jdbc:mysql://containers-us-west-26.railway.app:6001/railway?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
decorator:
  datasource:
    p6spy:
      enable-logging: false
logging:
  level:
    root: info
    c: error
    com.hjj.apiserver: info
