spring:
  profiles:
    active: local
    include: oauth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  #    show-sql: true
  jwt:
    secret: testTokenspaeratkgspeokrtgpaeokrgpaejrgoaeijrgoaeijrgfndkbjnrstghjsrteghjoaeorigjaeorigj
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4024KB
      max-request-size: 4024KB
  jackson:
    deserialization:
      fail-on-null-for-primitives: false
      fail-on-null-creator-properties: false
server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 65536
  error:
    whitelabel:
      enabled: false
management:
  endpoint:
    health:
      group:
        readiness:
          additional-path: server:/readyz
          include: ping, db
          status:
            http-mapping:
              up: 200
              unknown: 503
              down: 503
              out_of_service: 503
        liveness:
          additional-path: server:/livez
          include:
            - ping
          status:
            http-mapping:
              up: 200
              unknown: 503
              down: 503
              out_of_service: 503


--- #local
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 1000
      command-timeout: 5000
      batch-size: 1000
  datasource:
    url: jdbc:mariadb://localhost:3306/api_server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    username: mysqluser
    password: mysqlpw
decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  level:
    root: info
    c: error
    com.hjj.apiserver: debug

--- #prod
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      database: ${SPRING_REDIS_DATABASE}
      connect-timeout: ${SPRING_REDIS_CONNECT_TIMEOUT:1000}
      command-timeout: ${SPRING_REDIS_COMMAND_TIMEOUT:5000}
      batch-size: ${SPRING_REDIS_BATCH_SIZE:1000}
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SECRET_USERNAME}
    password: ${SECRET_PASSWORD}
decorator:
  datasource:
    p6spy:
      enable-logging: false
logging:
  level:
    root: info
    c: error
    com.hjj.apiserver: info
