spring:
  profiles:
    active: local
    include: oauth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100
#    show-sql: true
  jwt:
    scret: hjjJWT
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#    org:
#      hibernate:
#        SQL: debug
server:
  port: 8080

--- #local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/api_server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
      username: hjj1991
      password: wowjddl1
decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  level:
    com: debug

--- #prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://containers-us-west-26.railway.app:6001/railway?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
      username: root
      password: kHxLwtCsXafkwjWtaJae
decorator:
  datasource:
    p6spy:
      enable-logging: false
logging:
  level:
    com: info
