name: Kotlin CI with Gradle

on:
    push:
        branches:
            - 'releases-**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 21
              uses: actions/setup-java@v2
              with:
                  java-version: '21'
                  distribution: 'adopt'

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew build

            - name: Extract branch version
              id: extract_version
              run: echo "version=$(echo $GITHUB_REF | sed -n 's#refs/heads/releases-##p')" >> $GITHUB_OUTPUT

            - name: 도커 빌더 생성 및 부팅
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: 도커 이미지 빌드 및 푸시
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: Dockerfile
                  platforms: linux/arm64/v8
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/sundry-ninja:${{ env.version }}
        outputs:
            version: ${{ steps.extract_version.outputs.version }}

    update-helm-chart:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: actions/checkout@v2
              with:
                  repository: hjj1991/helm-charts
                  token: ${{ secrets.REPO_TOKEN }}
                  path: helm-charts

            - name: Update Helm values.yaml
              run: |
                  sed -i 's/tag: .*/tag: '"${{ needs.build.outputs.version }}"'/' helm-charts/api-server/values.yaml

            - name: Commit changes
              run: |
                  cd helm-charts
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add api-server/values.yaml
                  git commit -m "Update image tag to ${{ needs.build.outputs.version }}"
                  git push
