name: Kotlin CI with Gradle

on:
  push:
    branches:
      - 'releases-**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Extract branch version
      id: extract_version
      run: echo "::set-output name=version::$(echo $GITHUB_REF | sed -n 's#refs/heads/releases-##p')"

    - name: 도커 빌더 생성 및 부팅
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: 도커 이미지 빌드 및 푸시
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        platforms: linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sundry-ninja:${{ steps.extract_version.outputs.version }}

